# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#eae0e7"

# Title color for boxes
theme[title]="#e9b5ef"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#d6c0d6"

# Background color of selected item in processes box
theme[selected_bg]="#e9b5ef"

# Foreground color of selected item in processes box
theme[selected_fg]="#472150"

# Color of inactive/disabled text
theme[inactive_fg]="#cfc3cd"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#f5b7b0"

# Cpu box outline color
theme[cpu_box]="#988e97"

# Memory/disks box outline color
theme[mem_box]="#988e97"

# Net up/down box outline color
theme[net_box]="#988e97"

# Processes box outline color
theme[proc_box]="#988e97"

# Box divider line and small boxes line color
theme[div_line]="#4d444c"

# Temperature graph colors
theme[temp_start]="#d6c0d6"
theme[temp_mid]="#e9b5ef"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#d6c0d6"
theme[cpu_mid]="#e9b5ef"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#d6c0d6"
theme[free_mid]=""
theme[free_end]="#524153"

# Mem/Disk cached meter
theme[cached_start]="#f5b7b0"
theme[cached_mid]=""
theme[cached_end]="#673b36"

# Mem/Disk available meter
theme[available_start]="#e9b5ef"
theme[available_mid]=""
theme[available_end]="#603768"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#d6c0d6"
theme[download_mid]="#e9b5ef"
theme[download_end]="#f5b7b0"

# Upload graph colors
theme[upload_start]="#d6c0d6"
theme[upload_mid]="#e9b5ef"
theme[upload_end]="#f5b7b0"