[wallust]
; accent             = 1db954
accent             = ACA381
accent-active      = FCDA4E
accent-inactive    = BDA33A
banner             = ACA381
border-active      = FCDA4E
border-inactive    = BDA33A
header             = ACA381
highlight          = BF6B79
main               = 02121C
notification       = FA9666
notification-error = BC704D
subtext            = 
text               = FEF6D3
