[wallust]
; accent             = 1db954
accent             = 5B747A
accent-active      = 2C7D90
accent-inactive    = 2A6A7A
banner             = 5B747A
border-active      = 2C7D90
border-inactive    = 2A6A7A
header             = 5B747A
highlight          = 928145
main               = 021119
notification       = 38D6D9
notification-error = 2AA0A3
subtext            = 
text               = ADC7CD
