[wallust]
; accent             = 1db954
accent             = A35375
accent-active      = 5446AB
accent-inactive    = 5446AB
banner             = A35375
border-active      = 5446AB
border-inactive    = 5446AB
header             = A35375
highlight          = 874097
main               = 010103
notification       = 734498
notification-error = 734498
subtext            = 
text               = FA9BC1
