[config]

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar-colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = "pkill -SIGUSR2 waybar"

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel-colors.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.btop]
input_path = '~/.config/matugen/templates/btop-colors.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc-colors.txt'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty-colors.txt'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.neovim]
input_path = '~/.config/matugen/templates/nvim-colors.lua'
output_path = '~/.config/nvim/lua/plugins/base16.lua'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk3-colors.css'
output_path = '~/.local/share/themes/matugen/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk4-colors.css'
output_path = '~/.local/share/themes/matugen/gtk-4.0/gtk.css'
post_hook = '~/.config/matugen/post-hook-scripts/gtk-themes-reload.sh'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/lua/colors.lua'

[templates.spotify]
input_path = '~/.config/matugen/templates/spicetify-colors.ini'
output_path = '~/.config/spicetify/Themes/Sleek/color.ini'
post_hook = 'spicetify apply --no-restart &>/dev/null'

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux-colors.conf'
output_path = '~/.config/tmux/generated.conf'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-colors.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.zathura]
input_path = '~/.config/matugen/templates/zathura-colors.txt'
output_path = '~/.config/zathura/zathurarc'
