# colors for fuzzel application launcher
# You can use this template by adding the following to wallust.toml:
# fuzzel = { template = "fuzzel.ini", target = "~/.config/fuzzel/colors.ini" }
# and add the following to your foot.ini config
#
# [main]
# include=/home/USERNAME/.config/fuzzel/colors.ini

[colors]
background=#010003ff
text=#FA9BC1ff
prompt=#010103ff
placeholder=#5446ABff
input=#914284ff
match=#734498ff
selection=#944091ff
selection-text=#FA9BC1ff
selection-match=#C830B1ff
counter=#E388ADff
border=#A35375ff
