# colors for fuzzel application launcher
# You can use this template by adding the following to wallust.toml:
# fuzzel = { template = "fuzzel.ini", target = "~/.config/fuzzel/colors.ini" }
# and add the following to your foot.ini config
#
# [main]
# include=/home/USERNAME/.config/fuzzel/colors.ini

[colors]
background=#021119ff
text=#ADC7CDff
prompt=#00010Aff
placeholder=#2A6A7Aff
input=#486285ff
match=#2AA0A3ff
selection=#2D7B99ff
selection-text=#ADC7CDff
selection-match=#3371D0ff
counter=#82A6AFff
border=#5B747Aff
