# colors for fuzzel application launcher
# You can use this template by adding the following to wallust.toml:
# fuzzel = { template = "fuzzel.ini", target = "~/.config/fuzzel/colors.ini" }
# and add the following to your foot.ini config
#
# [main]
# include=/home/USERNAME/.config/fuzzel/colors.ini

[colors]
background=#02121Cff
text=#FEF6D3ff
prompt=#00010Bff
placeholder=#BDA33Aff
input=#B09A5Cff
match=#BC704Dff
selection=#509D7Aff
selection-text=#FEF6D3ff
selection-match=#F5BF39ff
counter=#F5E9B8ff
border=#ACA381ff
