$wallpaper = /home/coffee/Pictures/wallpapers/river_forrest.jpg
$background = rgb(02121C)
$foreground = rgb(FEF6D3)
$color0 = rgb(00010B)
$color1 = rgb(BDA33A)
$color2 = rgb(B09A5C)
$color3 = rgb(BC704D)
$color4 = rgb(509D7A)
$color5 = rgb(8F505E)
$color6 = rgb(189295)
$color7 = rgb(F5E9B8)
$color8 = rgb(ACA381)
$color9 = rgb(FCDA4E)
$color10 = rgb(EBCA7A)
$color11 = rgb(FA9666)
$color12 = rgb(6AD1A4)
$color13 = rgb(BF6B79)
$color14 = rgb(20C1C7)
$color15 = rgb(F5E9B8)
