source = ~/.config/hypr/variables.conf
source = ~/.config/hypr/colors.conf

general {
    hide_cursor = true 
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = $wallpaper
    blur_passes = 0
}

shape {
    monitor =
    size = 25%, 40%
    color = rgba(0, 0, 0, 0.4)
    rounding = 10
    position = 0, 0
    halign = center
    valign = center
    zindex = 1
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.1) # no fill

    outer_color = $color8 $color14 45deg
    check_color = $color7 $color13 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = $foreground
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    dots_spacing = 0.3

    position = 0, -100
    halign = center
    valign = center
    zindex = 2
}

# TIME
label {
    monitor =
    text = <span size='90pt'>$TIME</span>
    font_family = $font
    color = $foreground

    position = 0, 110
    halign = center
    valign = center
    zindex = 2
}

#DATE
label {
    monitor =
    text = cmd[update:60000] echo "<span size='24pt'>$(date +'%A, %d %B %Y')</span>"
    font_family = $font
    color = $foreground
    position = 0, 10
    halign = center
    valign = center
    zindex = 2
}
