#!/usr/bin/env bash
set -euo pipefail

source ~/dotfiles/scripts/variables.sh

systemctl --user enable --now wireplumber

DOTS="${HOME}/dotfiles/configs/user"

# NOTE: a "~" inside double quotes is NOT expanded by the
# shell - it stays a literal character, so the loop below
# would create a directory named "~" instead of linking
# anything. Always use "$HOME" when the path is quoted.
configs=(
	nvim ghostty dunst fuzzel waybar
	spicetify gtk-4.0 gtk-3.0
	zathura btop cava tmux yazi matugen
	eww hypr nwg-look qt6ct task
)
mkdir -p "${HOME}/.config"
for config in "${configs[@]}"; do
	rm -rf "${HOME}/.config/${config}"
	ln -s "${DOTS}/${config}" "${HOME}/.config/${config}"
done

# zsh is pointed at $XDG_CONFIG_HOME/zsh by /etc/zsh/zshenv
# (written by sys-conf.sh), so it reads $ZDOTDIR/.zshrc and
# no ~/.zshrc is needed - that keeps $HOME clean.
mkdir -p "${HOME}/.config/zsh"
ln -sf "${DOTS}/zsh/.zshrc" "${HOME}/.config/zsh/.zshrc"

# Hide launcher entries we never use. $XDG_DATA_HOME is
# searched BEFORE $XDG_DATA_DIRS and the first match for a
# given desktop file ID wins outright, so a local copy with
# NoDisplay=true shadows the one in /usr/share. Editing
# /usr/share directly would need root and would be undone
# by the next pacman upgrade of the owning package.
local_path="${HOME}/.local/share/applications"
usr_path="/usr/share/applications"
desktop_files=(
	xgps.desktop
	yazi.desktop
	lstopo.desktop
	xgpsspeed.desktop
	electron37.desktop
	xfce4-about.desktop
	google-maps-geo-handler.desktop
	avahi-discover.desktop
	bssh.desktop
	btop.desktop
	bvnc.desktop
)

mkdir -p "$local_path"
for dfile in "${desktop_files[@]}"; do
	# Not every entry's package is guaranteed to be installed
	[ -e "${usr_path}/${dfile}" ] || continue
	cp "${usr_path}/${dfile}" "${local_path}/${dfile}"
	# cp preserves the source mode, and a few entries in
	# /usr/share are 444 (e.g. cups.desktop), which would
	# make the edit below fail
	chmod u+w "${local_path}/${dfile}"
	if grep -q '^[#[:space:]]*NoDisplay=' "${local_path}/${dfile}"; then
		sed -i 's|^[#[:space:]]*NoDisplay=.*|NoDisplay=true|' "${local_path}/${dfile}"
	else
		echo 'NoDisplay=true' >> "${local_path}/${dfile}"
	fi
done

# Spicetify config
# After you log in to your spotify account
# run: spicetify backup apply
sudo chmod a+wr /opt/spotify
sudo chmod a+wr /opt/spotify/Apps -R

# Associate file types with proper applications
IMG_APP="org.gnome.eog.desktop"
PDF_APP="org.pwmt.zathura-pdf-mupdf.desktop"
VID_APP="mpv.desktop"
AUD_APP="mpv.desktop"
ARC_APP="org.gnome.FileRoller.desktop"

xdg-mime default "$PDF_APP" application/pdf
xdg-mime default "$PDF_APP" application/epub+zip
xdg-mime default "$PDF_APP" application/x-mobipocket-ebook
xdg-mime default "$PDF_APP" application/vnd.djvu

xdg-mime default "$ARC_APP" application/zip
xdg-mime default "$ARC_APP" application/zstd
xdg-mime default "$ARC_APP" application/x-zstd
xdg-mime default "$ARC_APP" application/x-xz
xdg-mime default "$ARC_APP" application/x-tar
xdg-mime default "$ARC_APP" application/x-rar
xdg-mime default "$ARC_APP" application/x-gzip
xdg-mime default "$ARC_APP" application/x-bzip2
xdg-mime default "$ARC_APP" application/x-7z-compressed

xdg-mime default "$IMG_APP" image/png
xdg-mime default "$IMG_APP" image/jpeg
xdg-mime default "$IMG_APP" image/webp
xdg-mime default "$IMG_APP" image/gif
xdg-mime default "$IMG_APP" image/bmp
xdg-mime default "$IMG_APP" image/svg+xml
xdg-mime default "$IMG_APP" image/tiff
xdg-mime default "$IMG_APP" image/avif

xdg-mime default "$VID_APP" video/mp4
xdg-mime default "$VID_APP" video/x-matroska
xdg-mime default "$VID_APP" video/webm
xdg-mime default "$VID_APP" video/x-msvideo
xdg-mime default "$VID_APP" video/quicktime
xdg-mime default "$VID_APP" video/3gpp
xdg-mime default "$VID_APP" video/mpeg
xdg-mime default "$VID_APP" video/ogg

xdg-mime default "$AUD_APP" audio/mp4
xdg-mime default "$AUD_APP" audio/flac
xdg-mime default "$AUD_APP" audio/wav
xdg-mime default "$AUD_APP" audio/aac
xdg-mime default "$AUD_APP" audio/mpeg
xdg-mime default "$AUD_APP" audio/ogg

# $WALLPAPER from variables.sh is the single source of
# truth for the wallpaper. hyprpaper and hyprlock cannot
# read it directly, so expand it once here into a hyprlang
# snippet that both of them source. It is written outside
# the repo on purpose - ~/.config/hypr is a symlink into
# the dotfiles, so generating it there would dirty git.
WALLPAPER_PATH="${HOME}/dotfiles/wallpapers/${WALLPAPER}"

mkdir -p "${HOME}/.local/state/hypr"
cat > "${HOME}/.local/state/hypr/wallpaper.conf" <<EOF
# Generated by user-conf.sh - do not edit.
# Change WALLPAPER in scripts/variables.sh and re-run instead.
\$wallpaper = ${WALLPAPER_PATH}
EOF

# wallust run "${WALLPAPER_PATH}"
matugen image "${WALLPAPER_PATH}"
